#Creates a CloudFormation template for the image API

from aws_cdk import (
    Duration,   #For lambda timeout
    Stack,
    aws_lambda,
    aws_apigateway,
    aws_s3,
    aws_iam #To specify the permissions/rights for the Lambda function
)
from constructs import Construct

class PyStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        images_bucket = aws_s3.Bucket(self, 'PY-ImagesPyBucket') #PY-ImagesPyBucket is not a name but a construct id
        #Name will automatically be generated by CDK

        images_lambda = aws_lambda.Function(
            self,
            "Py-ImageLambda",
            runtime=aws_lambda.Runtime.PYTHON_3_11,
            code=aws_lambda.Code.from_asset("services"),    #Looks into the services folder for the lambda function code
            handler="image.handler",
            timeout=Duration.seconds(30),
            environment={
                "BUCKET_NAME": images_bucket.bucket_name
            }
        )

        images_bucket.grant_read_write(images_lambda)

        #Add permissions to the Lambda function to invoke the Bedrock model
        images_lambda.add_to_role_policy(aws_iam.PolicyStatement(
            effect=aws_iam.Effect.ALLOW,    #Allow the Lambda function to invoke the model
            resources=["*"],
            actions=["bedrock:InvokeModel"]
        ))

        #Create a Rest API to invoke the Lambda function
        api = aws_apigateway.RestApi(self, "Py-ImageApi")

        #Create a resource for the API
        image_resource = api.root.add_resource("image")
        image_integration = aws_apigateway.LambdaIntegration(images_lambda)
        image_resource.add_method("POST", image_integration)


